module.exports = [
    {
        id: 1,
        name: "Enjoy Tattoos Los Angeles",
        city_id: 1,
        address: "contact artists for address",
        contact_info: {
            phone: "Not available",
            email: "email artists directly for appointments",
            other: "https://enjoytattoosla.com/pages/contact",
        },
        website: "https://enjoytattoosla.com/",
        hours: {
            monday: "Not available, contact artists directly",
            tuesday: "Not available, contact artists directly",
            wednesday: "Not available, contact artists directly",
            thursday: "Not available, contact artists directly",
            friday: "Not available, contact artists directly",
            saturday: "Not available, contact artists directly",
            sunday: "Not available, contact artists directly",
        },
        about: "Enjoy Tattoos La is a private studio owned and operated by Austin Maples. Enjoy Tattoos specializes in Classic and American Tradition designs. Austin Maples primarily works in Black and Gray. Enjoy Tattoos LA also has an array of Tattoo related merchandise for sale.",
        location: "Los Angeles, CA",
        instagram: "https://www.instagram.com/enjoy.tattoos.la/",
    },
    {
        id: 2,
        name: "Genuine Electric Tattoo",
        city_id: 1,
        address: "13725 Burbank Blvd, Van Nuys, CA 91401",
        contact_info: {
            phone: "818-582-3622",
            email: "genuineelectrictattoo@gmail.com",
            other: "Not available",
        },
        website: "https://www.facebook.com/genuineelectrictattoo",
        hours: {
            monday: "12:00pm to 8:00pm",
            tuesday: "12:00pm to 8:00pm",
            wednesday: "12:00pm to 8:00pm",
            thursday: "12:00pm to 8:00pm",
            friday: "12:00pm to 8:00pm",
            saturday: "12:00pm to 8:00pm",
            sunday: "12:00pm to 6:00pm",
        },
        about: "Tattoo shop specializing in American traditional. BOLD tattooing. No bullshit. Honest prices.",
        location: "13725 Burbank Blvd, Van Nuys, CA 91401",
        instagram: "https://www.instagram.com/genuine_electric_tattoo/",
    },
    {
        id: 3,
        name: "Iron Palm Tattoo Parlour",
        city_id: 1,
        address: "1800 N. Via Negocio #1, Palm Springs, CA 92262",
        contact_info: {
            phone: "760-898-7292",
            email: "No shop email, please call or contact artists directly",
            other: "http://ironpalmtattoo.com/contact",
        },
        website: "http://ironpalmtattoo.com/",
        hours: {
            monday: "12:00pm to 8:00pm",
            tuesday: "12:00pm to 8:00pm",
            wednesday: "12:00pm to 8:00pm",
            thursday: "12:00pm to 8:00pm",
            friday: "12:00pm to 8:00pm",
            saturday: "12:00pm to 8:00pm",
            sunday: "12:00pm to 6:00pm",
        },
        about: `Iron Palm was formed in 2016 by Coachella Valley natives: Wane Kan and Cody Cowan. Like any other duo in history (Method Man/Redman, Starsky and Hutch, etc.), they focus on their own parallel goal - which has always been, "Great Timeless Tattoos"`,
        location: "1800 N. Via Negocio #1, Palm Springs, CA 92262",
        instagram: "https://www.instagram.com/ironpalmtattooparlour/",
    },
    {
        id: 4,
        name: "MARY TATTOO",
        city_id: 1,
        address: "32 B Anacapa Santa Barbara, CA",
        contact_info: {
            phone: "805-859-4804",
            email: "No shop email, contact artists directly",
            other: "Not available",
        },
        website: "https://www.facebook.com/MARY-102680741608033/",
        hours: {
            monday: "Not available, contact artists directly",
            tuesday: "Not available, contact artists directly",
            wednesday: "Not available, contact artists directly",
            thursday: "Not available, contact artists directly",
            friday: "Not available, contact artists directly",
            saturday: "Not available, contact artists directly",
            sunday: "Not available, contact artists directly",
        },
        about: "Private tattoo and art studio of Vanae Rivera.",
        location: "32 B Anacapa Santa Barbara, CA 93101",
        instagram: "https://www.instagram.com/marytattoosb/",
    },
    {
        id: 5,
        name: "BOOM BOOM TATTOO ROOM",
        city_id: 1,
        address: "756 E Katella Ave, Orange, CA 92867",
        contact_info: {
            phone: "317-531-2223",
            email: "No shop email, DM artists on Instagram",
            other: "Not available",
        },
        website:
            "https://www.facebook.com/The-Boom-Boom-Tattoo-Room-122719164474971/?ref=page_internal",
        hours: {
            monday: "Not available, DM artists on Instagram",
            tuesday: "Not available, DM artists on Instagram",
            wednesday: "Not available, DM artists on Instagram",
            thursday: "Not available, DM artists on Instagram",
            friday: "Not available, DM artists on Instagram",
            saturday: "Not available, DM artists on Instagram",
            sunday: "Not available, DM artists on Instagram",
        },
        about: "COMMUNITY COLLECTIVE. TCB COME AS YOU ARE. FOR APPOINTMENTS DM INDIVIDUAL ARTIST",
        location: "756 E Katella Ave, Orange, CA 92867",
        instagram: "https://www.instagram.com/boomboomtattooroom/",
    },
    {
        id: 6,
        name: "Rose Land Tattoo",
        city_id: 1,
        address: "213 W. Commonwealth Fullerton, CA 92832",
        contact_info: {
            phone: "714-519-3743",
            email: "No shop email, contact artists directly",
            other: "https://www.roselandtattoo.com/contact",
        },
        website: "https://www.roselandtattoo.com/",
        hours: {
            monday: "closed",
            tuesday: "12:00pm to 8:00pm",
            wednesday: "12:00pm to 8:00pm",
            thursday: "12:00pm to 8:00pm",
            friday: "12:00pm to 8:00pm",
            saturday: "12:00pm to 8:00pm",
            sunday: "closed",
        },
        about: "Rose Land Tattoo is a world class, custom tattoo shop that prides themselves on superior quality tattooing as well as maintaining a friendly, clean environment while utilizing extensive training in the history, proper design principles and application of all types of tattoo imagery. Although focusing on american traditional design, versatility is always welcomed.",
        location: "213 W. Commonwealth Fullerton, CA 92832",
        instagram: "https://www.instagram.com/roselandtattoo/",
    },
    {
        id: 7,
        name: "The Honorable Society",
        city_id: 1,
        address: "8424 W Santa Monica Blvd West Hollywood, CA 90069",
        contact_info: {
            phone: "323-654-2440",
            email: "shop@thstattoo.com",
            other: "https://thehonorablesociety.com/request/",
        },
        website: "https://thehonorablesociety.com/",
        hours: {
            monday: "10:00am to 10:00pm",
            tuesday: "10:00am to 10:00pm",
            wednesday: "10:00am to 8:00pm",
            thursday: "10:00am to 10:00pm",
            friday: "10:00am to 10:00pm",
            saturday: "10:00am to 10:00pm",
            sunday: "10:00am to 10:00pm",
        },
        about: "The Honorable Society offers an eclectic style variety, encompassing American Traditional, Realism, Japanese, Neo Traditional, Thai Traditional, Illustrative, Watercolor, Fine Line, Minimalism, Chicano and Traditional Blackwork, we pride ourselves in being able to pair an artist to a customer with the exactly appropriate skillset.",
        location: "8424 W Santa Monica Blvd West Hollywood, CA 90069",
        instagram: "https://www.instagram.com/thstpl/",
    },
    {
        id: 8,
        name: "Dark Horse Tattoo Los Angeles",
        city_id: 1,
        address: "4644 Hollywood Blvd Los Angeles, CA 90027",
        contact_info: {
            phone: "323-665-7345",
            email: "darkhorsetattoola@gmail.com",
            other: "https://www.darkhorsetattoolosangeles.com/contact-us",
        },
        website: "https://www.darkhorsetattoolosangeles.com/",
        hours: {
            monday: "12:00pm to 9pm",
            tuesday: "12:00pm to 9pm",
            wednesday: "12:00pm to 9pm",
            thursday: "12:00pm to 9pm",
            friday: "12:00pm to 9pm",
            saturday: "12:00pm to 9pm",
            sunday: "12:00pm to 9pm",
        },
        about: "Bryan Burk opened Dark Horse Tattoo in 2010 with the intention of creating a non-intimidating relaxed atmosphere while adhering to the highest levels of craftsmanship and artistry. Bryan was soon joined by Adam Warmerdam, their stylish aesthetic and fresh approach to American and traditional Japanese tattooing quickly established them as one of the most sought after shops in the city.",
        location: "4644 Hollywood Blvd Los Angeles, CA 90027",
        instagram: "https://www.instagram.com/darkhorse_la/",
    },
    {
        id: 9,
        name: "Port City Tattoo Costa Mesa",
        city_id: 1,
        address: "1145 Baker st. #A, Costa Mesa, CA 92626",
        contact_info: {
            phone: "714-708-2120",
            email: "portcitytattoocm@gmail.com",
            other: "https://www.portcitytattoo.com/contact/",
        },
        website: "https://www.portcitytattoo.com/",
        hours: {
            monday: "11:00am to 8pm",
            tuesday: "11:00am to 8pm",
            wednesday: "11:00am to 8pm",
            thursday: "11:00am to 8pm",
            friday: "11:00am to 8pm",
            saturday: "11:00am to 8pm",
            sunday: "11:00am to 8pm",
        },
        about: "Tailored made tattoos at Long Beach, Costa Mesa, and Santa Ana.",
        location: "1145 Baker st. #A, Costa Mesa, CA 92626",
        instagram: "https://www.instagram.com/portcitytattooca/",
    },
    {
        id: 10,
        name: "Port City Tattoo Long Beach",
        city_id: 1,
        address: "4290 Outer Traffic Circle, Long Beach, CA 90804",
        contact_info: {
            phone: "562-494-6800",
            email: "portcitylb@gmail.com",
            other: "https://www.portcitytattoo.com/contact/",
        },
        website: "https://www.portcitytattoo.com/",
        hours: {
            monday: "11:00am to 8pm",
            tuesday: "11:00am to 8pm",
            wednesday: "11:00am to 8pm",
            thursday: "11:00am to 8pm",
            friday: "11:00am to 8pm",
            saturday: "11:00am to 8pm",
            sunday: "11:00am to 8pm",
        },
        about: "Tailored made tattoos at Long Beach, Costa Mesa, and Santa Ana.",
        location: "4290 Outer Traffic Circle, Long Beach, CA 90804",
        instagram: "https://www.instagram.com/portcitytattooca/",
    },
    {
        id: 11,
        name: "Port City Tattoo Santa Ana",
        city_id: 1,
        address: "419 N. Broadway, Santa Ana, CA 92701",
        contact_info: {
            phone: "657-231-6811",
            email: "portcitysa@gmail.com",
            other: "https://www.portcitytattoo.com/contact/",
        },
        website: "https://www.portcitytattoo.com/",
        hours: {
            monday: "11:00am to 8pm",
            tuesday: "11:00am to 8pm",
            wednesday: "11:00am to 8pm",
            thursday: "11:00am to 8pm",
            friday: "11:00am to 8pm",
            saturday: "11:00am to 8pm",
            sunday: "11:00am to 8pm",
        },
        about: "Tailored made tattoos at Long Beach, Costa Mesa, and Santa Ana.",
        location: "419 N. Broadway, Santa Ana, CA 92701",
        instagram: "https://www.instagram.com/portcitytattooca/",
    },
    {
        id: 12,
        name: "Spotlight Tattoo",
        city_id: 1,
        address: "5859 Melrose Ave, Los Angeles, CA, United States",
        contact_info: {
            phone: "323-871-1084",
            email: "charlierobertstattoo@gmail.com",
            other: "Not available",
        },
        website:
            "https://www.facebook.com/people/Bob-Charlie-Roberts-Spotlight-Tattoo/100063654006800/",
        hours: {
            monday: "1:00pm to 9pm",
            tuesday: "1:00pm to 9pm",
            wednesday: "1:00pm to 9pm",
            thursday: "1:00pm to 9pm",
            friday: "1:00pm to 9pm",
            saturday: "1:00pm to 9pm",
            sunday: "1:00pm to 9pm",
        },
        about: "Bob & Charlie Roberts’ World Famous Spotlight Tattoo. Est. 1982.",
        location: "5859 Melrose Ave, Los Angeles, CA",
        instagram: "https://www.instagram.com/worldfamousspotlighttattoo/",
    },
    {
        id: 13,
        name: "St. Marks Tattoo",
        city_id: 1,
        address: "4860 Santa Monica Blvd. Los Angeles, CA 90029",
        contact_info: {
            phone: "909-648-2683",
            email: "No shop email, call or text phone number",
            other: "Not available",
        },
        website: "https://www.stmarkstattoo.com/",
        hours: {
            monday: "Not available, contact shop for more info",
            tuesday: "Not available, contact shop for more info",
            wednesday: "Not available, contact shop for more info",
            thursday: "Not available, contact shop for more info",
            friday: "Not available, contact shop for more info",
            saturday: "Not available, contact shop for more info",
            sunday: "Not available, contact shop for more info",
        },
        about: "EST. 2017. Tattooing as you like it",
        location: "4860 Santa Monica Blvd. Los Angeles, CA 90029",
        instagram: "https://www.instagram.com/st.markstattoo_la/",
    },
    {
        id: 14,
        name: "10 Thousand Foxes Tattoo",
        city_id: 1,
        address: "7664 Melrose Ave, Los Angeles, CA 90046, United States",
        contact_info: {
            phone: "347-987-4304",
            email: "10thousandfoxesla@gmail.com",
            other: "https://www.10thousandfoxestattoo.com/booking-now/",
        },
        website: "https://www.10thousandfoxestattoo.com/los-angeles-home/#",
        hours: {
            monday: "12:00pm to 9:00pm",
            tuesday: "12:00pm to 9:00pm",
            wednesday: "12:00pm to 9:00pm",
            thursday: "12:00pm to 9:00pm",
            friday: "12:00pm to 9:00pm",
            saturday: "12:00pm to 9:00pm",
            sunday: "12:00pm to 9:00pm",
        },
        about: `We are a Los Angeles tattoo studio based in the heart of West Hollywood. We offer custom tattoo designs by our resident artists as well as a rotating roster of international guests. We aim to provide a friendly and comfortable environment for your tattoo experience, because our focus is to be the best tattoo studio in Los Angeles. From the moment you contact us to the hours we spend together on your tattoo; our goal is to collaborate and create unique, exclusive pieces just for you. We can’t wait to hear your ideas and look forward to working with you!`,
        location: "7664 Melrose Ave, Los Angeles, CA 90046, United States",
        instagram: "https://www.instagram.com/10thousandfoxestattoola/",
    },
];
