module.exports = [
    {
        id: 1,
        name: "Enjoy Tattoos Los Angeles",
        city_id: 1,
        address: "contact artists for address",
        contact_info: {
            phone: "not available",
            email: "email artists directly for appointments",
            other: "not available",
        },
        website: "https://enjoytattoosla.com/",
        hours: {
            monday: "not available, contact artists directly",
            tuesday: "not available, contact artists directly",
            wednesday: "not available, contact artists directly",
            thursday: "not available, contact artists directly",
            friday: "not available, contact artists directly",
            saturday: "not available, contact artists directly",
            sunday: "not available, contact artists directly",
        },
        about: "Enjoy Tattoos La is a private studio owned and operated by Austin Maples. Enjoy Tattoos specializes in Classic and American Tradition designs. Austin Maples primarily works in Black and Gray. Enjoy Tattoos LA also has an array of Tattoo related merchandise for sale.",
        location: "Los Angeles, CA",
        instagram: "https://www.instagram.com/enjoy.tattoos.la/",
    },
    {
        id: 2,
        name: "Genuine Electric Tattoo",
        city_id: 1,
        address: "13725 Burbank Blvd, Van Nuys, CA 91401",
        contact_info: {
            phone: "818-582-3622",
            email: "genuineelectrictattoo@gmail.com",
            other: "not available",
        },
        website: "https://www.facebook.com/genuineelectrictattoo",
        hours: {
            monday: "12:00pm to 8:00pm",
            tuesday: "12:00pm to 8:00pm",
            wednesday: "12:00pm to 8:00pm",
            thursday: "12:00pm to 8:00pm",
            friday: "12:00pm to 8:00pm",
            saturday: "12:00pm to 8:00pm",
            sunday: "12:00pm to 6:00pm",
        },
        about: "Tattoo shop specializing in American traditional. BOLD tattooing. No bullshit. Honest prices.",
        location: "13725 Burbank Blvd, Van Nuys, CA 91401",
        instagram: "https://www.instagram.com/genuine_electric_tattoo/",
    },
    {
        id: 3,
        name: "Iron Palm Tattoo Parlour",
        city_id: 1,
        address: "1800 N. Via Negocio #1, Palm Springs, CA 92262",
        contact_info: {
            phone: "760-898-7292",
            email: "No shop email, please call or contact artists directly",
            other: "not available",
        },
        website: "http://ironpalmtattoo.com/",
        hours: {
            monday: "12:00pm to 8:00pm",
            tuesday: "12:00pm to 8:00pm",
            wednesday: "12:00pm to 8:00pm",
            thursday: "12:00pm to 8:00pm",
            friday: "12:00pm to 8:00pm",
            saturday: "12:00pm to 8:00pm",
            sunday: "12:00pm to 6:00pm",
        },
        about: `Iron Palm was formed in 2016 by Coachella Valley natives: Wane Kan and Cody Cowan. Like any other duo in history (Method Man/Redman, Starsky and Hutch, etc.), they focus on their own parallel goal - which has always been, "Great Timeless Tattoos"`,
        location: "1800 N. Via Negocio #1, Palm Springs, CA 92262",
        instagram: "https://www.instagram.com/ironpalmtattooparlour/",
    },
];
